MvcMusicStore/MvcMusicStore/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcMusicStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var Cart = MvcMusicStore.Models.ShoppingCart.GetCart(this.HttpContext);
            var viewModel = new MvcMusicStore.ViewModels.ShoppingCartViewModel
            {
                CartItems=Cart.GetCartItems(),
                CartTotal =Cart.GetTotal()

            };
         
           
            return View(viewModel);
        }
        //Get:/Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            Maticsoft.BLL.album albumbll =new Maticsoft.BLL.album();

            var addedAlbum = albumbll.GetModel(id);
            var Cart = MvcMusicStore.Models.ShoppingCart.GetCart(this.HttpContext);
            Cart.AddToCart(addedAlbum);
            return RedirectToAction("Index");
        }
        //Ajax:/ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            var Cart = MvcMusicStore.Models.ShoppingCart.GetCart(this.HttpContext);
            Maticsoft.BLL.album albumbll =new Maticsoft.BLL.album();
            Maticsoft.BLL.cart cartbll = new Maticsoft.BLL.cart();
            string albumName = albumbll.GetModel(cartbll.GetModel(id).AlbumId).Title;
            int itemCount = Cart.RemoveFromCart(id);
            var results = new MvcMusicStore.ViewModels.ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(albumName) + " has been removed from your shopping cart.",
                CartTotal = Cart.GetTotal(),
                CartCount = Cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        //Get:/ShoppingCart/CartSummary/
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var Cart = MvcMusicStore.Models.ShoppingCart.GetCart(this.HttpContext);
            ViewData["CartCount"] = Cart.GetCount();
            return PartialView("CartSummary");
        }
	}
}

MvcMusicStore/MvcMusicStore/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Maticsoft.Model;
using System.Data.Entity;
using Maticsoft.BLL;
using System.Data;

namespace MvcMusicStore.Controllers
{
    public class StoreController : Controller
    {
     //   MusicStoreEntities storeDb = new MusicStoreEntities();
     //   mymusicEntities mydb = new mymusicEntities();
        //
        // GET: /Store/
        Maticsoft.BLL.genre genrebll = new Maticsoft.BLL.genre();
        public ActionResult Index()
        {
         //   Database.SetInitializer(new DropCreateDatabaseIfModelChanges<MusicStoreEntities>());
            /*
            var genres = new List<Genre>{
                new Genre{Name="Disco"},
                new Genre{Name="Jazz"},
                new Genre{Name="Rock"}
            };
             */
        //    storeDb.Genres.Add(new Genre{Name="小李子" ,Description="演员"});
       //     storeDb.SaveChanges();
           
         //   var genres = storeDb.Genres.ToList();
           // var genres = mydb.genre.ToList();
          
            var genres = genrebll.GetModelList("1=1");

            return View(genres);
           
        }
        public ActionResult Browse(string genre)
        {
        //    string message = HttpUtility.HtmlEncode("store.browse,Genre=" + genre);
          //  var genreModel = new genre { Name = genre };
            string sqlcmd = String.Format(@"Name='{0:s}'", genre);
            var genreModel = genrebll.GetgenreWithAlbum(sqlcmd);
            return View(genreModel);
        }
        public ActionResult Details( int id)
        {
          //  string message = "Store.Details.id=" + id;
       //     var album = new album { Title = "Album" + id };
            Maticsoft.BLL.album albumbll = new Maticsoft.BLL.album();
            var Album= albumbll.GetModelAll(id);
            return View(Album);
        }
        [ChildActionOnly]
        public ActionResult GenreMenu()
        {
            var genres = genrebll.GetModelList("1=1");
            /*
            var genres = new List<Maticsoft.Model.genre>{
                new Maticsoft.Model.genre{GenreId=1,Name="Disco"},
                new Maticsoft.Model.genre{GenreId=2,Name="Jazz"},
                new Maticsoft.Model.genre{GenreId=4,Name="Rock"}
              };*/
            return PartialView(genres);
        }

    }
}

MvcMusicStore/MvcMusicStore/Views/Store/Browse.cshtml
@model  IEnumerable< Maticsoft.Model.genre>

@{
    ViewBag.Title = "Browse";
}

</br>
<div class="genre">
  
@foreach (var item in Model)
{
    <h2><em>专辑类型 @item.Name</em></h2>
    <ul id="album-list">
     @foreach(var album in item.Albums)
    {
         <li>
             <a href="@Url.Action("Details", new { id=album.AlbumId})">
                 <img alt="@album.Title" src="@album.AlbumArtUrl" />
                 <span>@album.Title</span>
             </a>
           
         </li>

     }
    </ul>
}
</div>

MvcMusicStore/MvcMusicStore/Views/Store/Details.cshtml
@model Maticsoft.Model.album

@{
    ViewBag.Title = "Album"+Model.Title;
}

<h2>Album:@Model.Title</h2>
<p>
    <img  alt="@Model.Title" src="@Model.AlbumArtUrl"/>
</p>
<div id ="album-details">
 <p>
        <em>Genre:</em> @Model.genrename
    </p>
    <p>
        <em>Artist:</em> @Model.artistname
    </p>
    <p>
        <em>Price:</em> @String.Format("{0:F}", Model.Price)
    </p>
    <p class="button">
        @Html.ActionLink("Add to cart", "AddToCart", "ShoppingCart", new { id = Model.AlbumId }, "")
    </p>
</div>

MvcMusicStore/MvcMusicStore/Views/Store/GenreMenu.cshtml
@model IEnumerable<Maticsoft.Model.genre>

<ui id="categories">
 @foreach (var item in Model)
 {
     <li>@Html.ActionLink(item.Name, "Browse", "Store", new { Genre=item.Name},null)</li> 
 }    
</ui>

MvcMusicStore/MvcMusicStore/Views/Store/Index.cshtml
@model IEnumerable<Maticsoft.Model.genre>

@{
    ViewBag.Title = "商场";
}
<h3> 音乐类型</h3>
<p>分类数量：@Model.Count() </p>
<ul>
    @foreach (var genre in Model)
    {
      
        <li>@Html.ActionLink(genre.Name, "Browse", new { genre=genre.Name})</li>
    }
</ul>